### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by dvpetta** [pyasi/crypto-bot#5]
Thanks for putting this together but I'm hoping you can help me as I can't seem to get it to work.

I've installed the app in my slack workspace and tried a number of commands but nothing is working.

![image](https://user-images.githubusercontent.com/19885577/133280548-f683f6df-998c-42b4-9306-3c01c056f13c.png)

Thanks

**Comment by pezzullig** [comment]
i am having the same issue
